---DIMENSIONAL TABLES---
-- 1. Дата (розширена)
CREATE TABLE dim_date (
    date_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_date DATE UNIQUE NOT NULL,
    year NUMBER(4) NOT NULL,
    quarter NUMBER(1) NOT NULL,
    month NUMBER(2) NOT NULL,
    month_name VARCHAR2(20),
    day NUMBER(2) NOT NULL,
    day_of_week NUMBER(1),
    is_weekend NUMBER(1) DEFAULT 0
);

-- 2. Країна 
CREATE TABLE dim_country (
    country_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    country_name VARCHAR2(100) UNIQUE NOT NULL,
    country_code CHAR(3) 
    --valid_from DATE DEFAULT SYSDATE,
    --valid_to DATE DEFAULT DATE '9999-12-31',
    --is_current NUMBER(1) DEFAULT 1 CHECK (is_current IN (0,1)),
    --load_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 3. Тип активу (довідкова таблиця)
CREATE TABLE dim_asset_type (
    asset_type_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_type_name VARCHAR2(50) NOT NULL UNIQUE
);

-- 4. Галузь (довідкова таблиця)
CREATE TABLE dim_industry (
    industry_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    industry_name VARCHAR2(100),
    industry_tag VARCHAR2(100) UNIQUE
);

-- 5. Актив (акції + крипто) 
CREATE TABLE dim_asset (
    asset_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_symbol VARCHAR2(50)UNIQUE NOT NULL, -- natural key
    asset_name VARCHAR2(200) NOT NULL,
    country_id NUMBER REFERENCES dim_country(country_id),
    industry_id NUMBER REFERENCES dim_industry(industry_id),  -- NULL для крипто
    asset_type_id NUMBER NOT NULL REFERENCES dim_asset_type(asset_type_id)   -- FK
    --valid_from DATE DEFAULT SYSDATE,
    --valid_to DATE DEFAULT DATE '9999-12-31',
    --is_current NUMBER(1) DEFAULT 1 CHECK (is_current IN (0,1)),
    --load_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 6. Індикатор (ВВП, інфляція, безробіття, реальна ставка)
CREATE TABLE dim_indicator (
    indicator_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    indicator_name VARCHAR2(200) UNIQUE NOT NULL,
    indicator_code VARCHAR2(50)
);

-- 7. Демографічний зріз (для безробіття)
CREATE TABLE dim_demographic_slice (
    demographic_slice_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sex VARCHAR2(20),
    age_group VARCHAR2(50),
    age_categories VARCHAR2(50),
    UNIQUE (sex, age_group, age_categories)
);


---FACT TABLES---
CREATE TABLE fact_asset_performance (
    date_id NUMBER NOT NULL REFERENCES dim_date(date_id),
    --country_id NUMBER NOT NULL REFERENCES dim_country(country_id), -- SCD2
    asset_id NUMBER NOT NULL REFERENCES dim_asset(asset_id), -- SCD2
    open_price NUMBER,
    high_price NUMBER,
    low_price NUMBER,
    close_price NUMBER,
    volume NUMBER,
    daily_return NUMBER,
    load_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_fact_asset_performance PRIMARY KEY (date_id, asset_id)
);

CREATE TABLE fact_macro_indicators (
    date_id NUMBER NOT NULL REFERENCES dim_date(date_id),
    country_id NUMBER NOT NULL REFERENCES dim_country(country_id), -- SCD2
    indicator_id NUMBER NOT NULL REFERENCES dim_indicator(indicator_id),
    demographic_slice_id NUMBER REFERENCES dim_demographic_slice(demographic_slice_id),
    value NUMBER NOT NULL,
    load_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_fact_macro_indicators PRIMARY KEY (date_id, country_id, indicator_id)
);
