-- Stage для всіх активів (stocks + crypto)

CREATE TABLE stg_assets (
    load_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trade_date DATE,
    open_price NUMBER,
    high_price NUMBER,
    low_price NUMBER,
    close_price NUMBER,
    volume NUMBER,
    ticker VARCHAR2(50),
    asset_name VARCHAR2(200),  -- brand_name або name з crypto
    asset_type VARCHAR2(20), -- Stock або Crypto
    country VARCHAR2(100),
    industry_tag VARCHAR2(100),
    dividends NUMBER,
    stock_splits NUMBER,
    daily_return NUMBER,
    load_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE stg_gdp (
    load_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    country VARCHAR2(100),
    country_code CHAR(3),
    year_date DATE, -- рік як дата (наприклад 2022-01-01)
    gdp_value NUMBER,
    indicator_name VARCHAR2(200),
    load_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE stg_inflation (
    load_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    country VARCHAR2(100),
    indicator_name VARCHAR2(200),
    year_date DATE,
    inflation_value NUMBER,
    load_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE stg_unemployment (
    load_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    country VARCHAR2(100),
    indicator_name VARCHAR2(200),
    sex VARCHAR2(20),
    age_group VARCHAR2(50),
    age_categories VARCHAR2(50),
    year_date DATE,
    unemployment_rate NUMBER,
    load_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE stg_real_interest (
    load_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    country_code CHAR(3),
    country VARCHAR2(100),
    year_date DATE,
    real_interest_rate NUMBER,
    indicator_name VARCHAR2(200),
    load_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


SELECT table_name FROM user_tables WHERE table_name LIKE 'STG_%';